#  NOTE: to reflect changes run $ pnpm codegen 

query AnilistMedia (
    $page: Int,
    $perPage: Int = 6,
    $type: MediaType,
    $search: String,
    $genre_in: [String],
    $season: MediaSeason,
    $seasonYear: Int,
    $format_in: [MediaFormat],
    $status_in: [MediaStatus],
    $sort: [MediaSort],
    ) {
    Page(page: $page, perPage: $perPage) {
        media(
            type: $type
            search: $search
            genre_in: $genre_in
            season: $season
            seasonYear: $seasonYear
            format_in: $format_in
            status_in: $status_in
            sort: $sort
            isAdult: false

            ) {
            id
            title {
                romaji
                english
            }
            coverImage {
                extraLarge
            }
            genres
            format
            status
            bannerImage
            description(asHtml: true)
            season
            seasonYear
            averageScore
            popularity
            episodes
            studios(isMain: true) {
                nodes {
                    name
                }
            }
            nextAiringEpisode {
                airingAt,
                timeUntilAiring
                episode
            }
        }
        pageInfo {
            total
            perPage
            currentPage
            lastPage
            hasNextPage
        }
    }
}
